/*
 DMXzone Nivo Slider
 Version: 3.0.2
 (c) 2015 DMXzone.com
 @build 25-02-2015 10:10:59
*/
(function(b){var y={};b.fn.dmxNivoSlider=function(r){if("string"===typeof r){var u=this.find(".nivoSlider").data("nivoslider"),e=Array.prototype.slice.call(arguments,1);u&&u[r]&&u[r].apply(u,e);return this}var q=b.extend({},y,r),a=this,k=this[0].id,n=b.dmxDataBindings;q.afterLoad=function(){var a=this.getSlider().find("img:eq("+this.getCurrentSlide()+")").parent("a");b(a).data("onshow")&&(new Function(b(a).data("onshow"))).call(this)};q.beforeChange=function(){var a=this.getSlider().find("img:eq("+
this.getCurrentSlide()+")").parent("a");b(a).data("onhide")&&(new Function(b(a).data("onhide"))).call(this)};q.afterChange=function(){var a=this.getSlider().find("img:eq("+this.getCurrentSlide()+")").parent("a");b(a).data("onshow")&&(new Function(b(a).data("onshow"))).call(this)};q.controlNavThumbs&&(q.controlNav=!0);n&&q.repeatElement?n.globalScope.watch(q.repeatElement,function(e){var r=a.find(".nivoSlider").data("nivoslider");r&&r.destroy();a.empty();if(e&&e.length){var h=b('<div class="nivoSlider"></div>').appendTo(a),
t=0;b.each(e,function(a,e){var m={},p=new n.Scope;p.set(e);for(var s in q.dynSlides)q.dynSlides[s]&&(m[s]=n.$parseTemplate(q.dynSlides[s],p));m.url&&(p=b('<img src="'+m.url+'">'),m.width&&p.attr("width",m.width),m.height&&p.attr("height",m.height),m.thumb&&p.attr("data-thumb",m.thumb),m.transition&&p.attr("data-transition",m.transition),m.title&&(m.description?(s=k+"_"+ ++t,h.after('<div id="'+s+'" class="nivo-html-caption"><h4>'+m.title+"</h4><p>"+m.description+"</p></div>"),p.attr("title","#"+s)):
p.attr("title",m.title)),h.append(p),m.link||m.onclick||m.onhide||m.onshow||m.onmouseover||m.onmouseout)&&(s=b('<a href="'+(m.link||"javascript:void(0);")+'">'),m.target&&s.attr("target",m.target),m.onclick&&s.attr("onclick",m.onclick),m.onhide&&s.attr("data-onhide",m.onhide),m.onshow&&s.attr("data-onshow",m.onshow),m.onmouseover&&s.attr("onmouseover",m.onmouseover),m.onmouseout&&s.attr("onmouseout",m.onmouseout),p.wrap(s))});h.nivoSlider(q)}}):a.find(".nivoSlider").nivoSlider(q)}})(jQuery);
(function(b){var y=function(r,u){var e=b.extend({},b.fn.nivoSlider.defaults,u),q=this,a={currentSlide:0,currentImage:"",totalSlides:0,running:!1,paused:!1,stop:!1,controlNavEl:!1},k=b(r);k.data("nivo:vars",a).addClass("nivoSlider");var n=k.children();n.each(function(){var c=b(this),w="";c.is("img")||(c.is("a")&&(c.addClass("nivo-imageLink"),w=c),c=c.find("img:first"));var d=0===d?c.attr("width"):c.width(),e=0===e?c.attr("height"):c.height();""!==w&&w.css("display","none");c.css("display","none");
a.totalSlides++});e.randomStart&&(e.startSlide=Math.floor(Math.random()*a.totalSlides));0<e.startSlide&&(e.startSlide>=a.totalSlides&&(e.startSlide=a.totalSlides-1),a.currentSlide=e.startSlide);b(n[a.currentSlide]).is("img")?a.currentImage=b(n[a.currentSlide]):a.currentImage=b(n[a.currentSlide]).find("img:first");b(n[a.currentSlide]).is("a")&&b(n[a.currentSlide]).css("display","block");var v=b("<img/>").addClass("nivo-main-image");v.attr("src",a.currentImage.attr("src")).show();k.append(v);b(window).resize(function(){k.children("img").width(k.width());
v.attr("src",a.currentImage.attr("src"));v.stop().height("auto");b(".nivo-slice").remove();b(".nivo-box").remove()});k.append(b('<div class="nivo-caption"></div>'));var y=function(c){var w=b(".nivo-caption",k);if(""!=a.currentImage.attr("title")&&void 0!=a.currentImage.attr("title")){var d=a.currentImage.attr("title");"#"==d.substr(0,1)&&(d=b(d).html());"block"==w.css("display")?setTimeout(function(){w.html(d)},c.animSpeed):(w.html(d),w.stop().fadeIn(c.animSpeed))}else w.stop().fadeOut(c.animSpeed)};
y(e);var h=0;!e.manualAdvance&&1<n.length&&(h=setInterval(function(){p(k,n,e,!1)},e.pauseTime));e.directionNav&&(k.append('<div class="nivo-directionNav"><a class="nivo-prevNav">'+e.prevText+'</a><a class="nivo-nextNav">'+e.nextText+"</a></div>"),b(k).on("click","a.nivo-prevNav",function(){if(a.running)return!1;clearInterval(h);h="";a.currentSlide-=2;p(k,n,e,"prev")}),b(k).on("click","a.nivo-nextNav",function(){if(a.running)return!1;clearInterval(h);h="";p(k,n,e,"next")}));if(e.controlNav){a.controlNavEl=
b('<div class="nivo-controlNav"></div>');k.after(a.controlNavEl);for(var t=0;t<n.length;t++)if(e.controlNavThumbs){a.controlNavEl.addClass("nivo-thumbs-enabled");var z=n.eq(t);z.is("img")||(z=z.find("img:first"));z.attr("data-thumb")&&a.controlNavEl.append('<a class="nivo-control" rel="'+t+'"><img src="'+z.attr("data-thumb")+'" alt="" /></a>')}else a.controlNavEl.append('<a class="nivo-control" rel="'+t+'">'+(t+1)+"</a>");b("a:eq("+a.currentSlide+")",a.controlNavEl).addClass("active");b("a",a.controlNavEl).bind("click",
function(){if(a.running||b(this).hasClass("active"))return!1;clearInterval(h);h="";v.attr("src",a.currentImage.attr("src"));a.currentSlide=b(this).attr("rel")-1;p(k,n,e,"control")})}e.pauseOnHover&&k.hover(function(){a.paused=!0;clearInterval(h);h=""},function(){a.paused=!1;""!==h||e.manualAdvance||(h=setInterval(function(){p(k,n,e,!1)},e.pauseTime))});k.bind("nivo:animFinished",function(){v.attr("src",a.currentImage.attr("src"));a.running=!1;b(n).each(function(){b(this).is("a")&&b(this).css("display",
"none")});b(n[a.currentSlide]).is("a")&&b(n[a.currentSlide]).css("display","block");""!==h||a.paused||e.manualAdvance||(h=setInterval(function(){p(k,n,e,!1)},e.pauseTime));e.afterChange.call(q)});var x=function(c,a,d){b(d.currentImage).parent().is("a")&&b(d.currentImage).parent().css("display","block");b('img[src="'+d.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(c.width()).css("visibility","hidden").show();for(var e=b('img[src="'+d.currentImage.attr("src")+'"]',
c).not(".nivo-main-image,.nivo-control img").parent().is("a")?b('img[src="'+d.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").parent().height():b('img[src="'+d.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height(),f=0;f<a.slices;f++){var g=Math.round(c.width()/a.slices);f===a.slices-1?c.append(b('<div class="nivo-slice" name="'+f+'"><img src="'+d.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block !important; top:0; left:-"+
(g+f*g-g)+'px;" /></div>').css({left:g*f+"px",width:c.width()-g*f+"px",height:e+"px",opacity:"0",overflow:"hidden"})):c.append(b('<div class="nivo-slice" name="'+f+'"><img src="'+d.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block !important; top:0; left:-"+(g+f*g-g)+'px;" /></div>').css({left:g*f+"px",width:g+"px",height:e+"px",opacity:"0",overflow:"hidden"}))}b(".nivo-slice",c).height(e);v.stop().animate({height:b(d.currentImage).height()},a.animSpeed)},
m=function(c,a,d){b(d.currentImage).parent().is("a")&&b(d.currentImage).parent().css("display","block");b('img[src="'+d.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(c.width()).css("visibility","hidden").show();for(var e=Math.round(c.width()/a.boxCols),f=Math.round(b('img[src="'+d.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height()/a.boxRows),g=0;g<a.boxRows;g++)for(var l=0;l<a.boxCols;l++)l===a.boxCols-1?c.append(b('<div class="nivo-box" name="'+
l+'" rel="'+g+'"><img src="'+d.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block; top:-"+f*g+"px; left:-"+e*l+'px;" /></div>').css({opacity:0,left:e*l+"px",top:f*g+"px",width:c.width()-e*l+"px"})):c.append(b('<div class="nivo-box" name="'+l+'" rel="'+g+'"><img src="'+d.currentImage.attr("src")+'" style="position:absolute; width:'+c.width()+"px; height:auto; display:block; top:-"+f*g+"px; left:-"+e*l+'px;" /></div>').css({opacity:0,left:e*l+"px",
top:f*g+"px",width:e+"px"})),b('.nivo-box[name="'+l+'"]',c).height(b('.nivo-box[name="'+l+'"] img',c).height()+"px");v.stop().animate({height:b(d.currentImage).height()},a.animSpeed)},p=function(c,a,d,e){var f=c.data("nivo:vars");f&&f.currentSlide===f.totalSlides-1&&d.lastSlide.call(q);if((!f||f.stop)&&!e)return!1;d.beforeChange.call(q);e?("prev"===e&&v.attr("src",f.currentImage.attr("src")),"next"===e&&v.attr("src",f.currentImage.attr("src"))):v.attr("src",f.currentImage.attr("src"));f.currentSlide++;
f.currentSlide===f.totalSlides&&(f.currentSlide=0,d.slideshowEnd.call(q));0>f.currentSlide&&(f.currentSlide=f.totalSlides-1);b(a[f.currentSlide]).is("img")?f.currentImage=b(a[f.currentSlide]):f.currentImage=b(a[f.currentSlide]).find("img:first");d.controlNav&&(b("a",f.controlNavEl).removeClass("active"),b("a:eq("+f.currentSlide+")",f.controlNavEl).addClass("active"));y(d);b(".nivo-slice",c).remove();b(".nivo-box",c).remove();var g=d.effect;a="";"random"===d.effect&&(a="sliceDownRight sliceDownLeft sliceUpRight sliceUpLeft sliceUpDown sliceUpDownLeft fold fade boxRandom boxRain boxRainReverse boxRainGrow boxRainGrowReverse".split(" "),
g=a[Math.floor(Math.random()*(a.length+1))],void 0===g&&(g="fade"));-1!==d.effect.indexOf(",")&&(a=d.effect.split(","),g=a[Math.floor(Math.random()*a.length)],void 0===g&&(g="fade"));f.currentImage.attr("data-transition")&&(g=f.currentImage.attr("data-transition"));f.running=!0;var l=0,h=0,k=a="",n="";a="";if("sliceDown"===g||"sliceDownRight"===g||"sliceDownLeft"===g)x(c,d,f),h=l=0,a=b(".nivo-slice",c),"sliceDownLeft"===g&&(a=b(".nivo-slice",c)._reverse()),a.each(function(){var a=b(this);a.css({top:"0px"});
h===d.slices-1?setTimeout(function(){a.animate({opacity:"1.0"},d.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){a.animate({opacity:"1.0"},d.animSpeed)},100+l);l+=50;h++});else if("sliceUp"===g||"sliceUpRight"===g||"sliceUpLeft"===g)x(c,d,f),h=l=0,a=b(".nivo-slice",c),"sliceUpLeft"===g&&(a=b(".nivo-slice",c)._reverse()),a.each(function(){var a=b(this);a.css({bottom:"0px"});h===d.slices-1?setTimeout(function(){a.animate({opacity:"1.0"},d.animSpeed,"",function(){c.trigger("nivo:animFinished")})},
100+l):setTimeout(function(){a.animate({opacity:"1.0"},d.animSpeed)},100+l);l+=50;h++});else if("sliceUpDown"===g||"sliceUpDownRight"===g||"sliceUpDownLeft"===g){x(c,d,f);var p=h=l=0;a=b(".nivo-slice",c);"sliceUpDownLeft"===g&&(a=b(".nivo-slice",c)._reverse());a.each(function(){var a=b(this);0===h?(a.css("top","0px"),h++):(a.css("bottom","0px"),h=0);p===d.slices-1?setTimeout(function(){a.animate({opacity:"1.0"},d.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){a.animate({opacity:"1.0"},
d.animSpeed)},100+l);l+=50;p++})}else if("fold"===g)x(c,d,f),h=l=0,b(".nivo-slice",c).each(function(){var a=b(this),e=a.width();a.css({top:"0px",width:"0px"});h===d.slices-1?setTimeout(function(){a.animate({width:e,opacity:"1.0"},d.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){a.animate({width:e,opacity:"1.0"},d.animSpeed)},100+l);l+=50;h++});else if("fade"===g)x(c,d,f),k=b(".nivo-slice:first",c),k.css({width:c.width()+"px"}),k.animate({opacity:"1.0"},2*d.animSpeed,
"",function(){c.trigger("nivo:animFinished")});else if("slideInRight"===g)x(c,d,f),k=b(".nivo-slice:first",c),k.css({width:"0px",opacity:"1"}),k.animate({width:c.width()+"px"},2*d.animSpeed,"",function(){c.trigger("nivo:animFinished")});else if("slideInLeft"===g)x(c,d,f),k=b(".nivo-slice:first",c),k.css({width:"0px",opacity:"1",left:"",right:"0px"}),k.animate({width:c.width()+"px"},2*d.animSpeed,"",function(){k.css({left:"0px",right:""});c.trigger("nivo:animFinished")});else if("boxRandom"===g)m(c,
d,f),n=d.boxCols*d.boxRows,l=h=0,a=s(b(".nivo-box",c)),a.each(function(){var a=b(this);h===n-1?setTimeout(function(){a.animate({opacity:"1"},d.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){a.animate({opacity:"1"},d.animSpeed)},100+l);l+=20;h++});else if("boxRain"===g||"boxRainReverse"===g||"boxRainGrow"===g||"boxRainGrowReverse"===g){m(c,d,f);var n=d.boxCols*d.boxRows,r=l=h=0,t=0,u=[];u[r]=[];a=b(".nivo-box",c);if("boxRainReverse"===g||"boxRainGrowReverse"===
g)a=b(".nivo-box",c)._reverse();a.each(function(){u[r][t]=b(this);t++;t===d.boxCols&&(r++,t=0,u[r]=[])});for(f=0;f<2*d.boxCols;f++){a=f;for(e=0;e<d.boxRows;e++)0<=a&&a<d.boxCols&&(function(a,e,f,h,l){var k=b(u[a][e]),m=k.width(),n=k.height();"boxRainGrow"!==g&&"boxRainGrowReverse"!==g||k.width(0).height(0);h===l-1?setTimeout(function(){k.animate({opacity:"1",width:m,height:n},d.animSpeed/1.3,"",function(){c.trigger("nivo:animFinished")})},100+f):setTimeout(function(){k.animate({opacity:"1",width:m,
height:n},d.animSpeed/1.3)},100+f)}(e,a,l,h,n),h++),a--;l+=100}}},s=function(a){for(var b,d,e=a.length;e;b=parseInt(Math.random()*e,10),d=a[--e],a[e]=a[b],a[b]=d);return a},A=function(a){this.console&&"undefined"!==typeof console.log&&console.log(a)};this.stop=function(){b(r).data("nivo:vars").stop||(b(r).data("nivo:vars").stop=!0,A("Stop Slider"))};this.start=function(){b(r).data("nivo:vars").stop&&(b(r).data("nivo:vars").stop=!1,A("Start Slider"))};this.prev=function(){a.running||(clearInterval(h),
h="",a.currentSlide-=2,p(k,n,e,"prev"))};this.next=function(){a.running||(clearInterval(h),h="",p(k,n,e,"next"))};this.first=function(){a.running||(clearInterval(h),h="",a.currentSlide=-1,p(k,n,e,"control"))};this.last=function(){a.running||(clearInterval(h),h="",a.currentSlide=a.totalSlides-2,p(k,n,e,"control"))};this["goto"]=function(b){a.running||(clearInterval(h),h="",v.attr("src",a.currentImage.attr("src")),a.currentSlide=b-1,p(k,n,e,"control"))};this.isRunning=function(){return a.running};this.isStopped=
function(){return a.stop};this.isPaused=function(){return a.paused};this.getSlider=function(){return k};this.getCurrentSlide=function(){return a.currentSlide};this.getTotalSlides=function(){return a.totalSlides};this.destroy=function(){clearInterval(h);h="";k.remove()};e.afterLoad.call(this);return this};b.fn.nivoSlider=function(r){return this.each(function(u,e){var q=b(this);if(q.data("nivoslider"))return q.data("nivoslider");var a=new y(this,r);q.data("nivoslider",a)})};b.fn.nivoSlider.defaults=
{effect:"random",slices:15,boxCols:8,boxRows:4,animSpeed:500,pauseTime:3E3,startSlide:0,directionNav:!0,controlNav:!0,controlNavThumbs:!1,pauseOnHover:!0,manualAdvance:!1,prevText:"Prev",nextText:"Next",randomStart:!1,beforeChange:function(){},afterChange:function(){},slideshowEnd:function(){},lastSlide:function(){},afterLoad:function(){}};b.fn._reverse=[].reverse})(jQuery);
